"""FactEngine FBM metamodel Pydantic package."""

from .models import (
    ConceptInstance,
    ConceptInstanceFlag,
    ConceptType,
    EntityType,
    Fact,
    FactData,
    FactType,
    FactTypeReading,
    FBMBaseModel,
    FBMDataType,
    FBMModel,
    JoinPath,
    Model,
    ModelNote,
    Page,
    PredicatePart,
    Role,
    RoleConstraint,
    RoleConstraintArgument,
    RoleConstraintRole,
    RoleReference,
    SubtypeRelationship,
    Synonym,
    ValueType,
)
from .xml import from_xml, load_fbm, save_fbm, to_xml

__all__ = [
    "ConceptInstance",
    "ConceptInstanceFlag",
    "ConceptType",
    "EntityType",
    "Fact",
    "FactData",
    "FactType",
    "FactTypeReading",
    "FBMBaseModel",
    "FBMDataType",
    "FBMModel",
    "JoinPath",
    "Model",
    "ModelNote",
    "Page",
    "PredicatePart",
    "Role",
    "RoleConstraint",
    "RoleConstraintArgument",
    "RoleConstraintRole",
    "RoleReference",
    "SubtypeRelationship",
    "Synonym",
    "ValueType",
    "from_xml",
    "load_fbm",
    "save_fbm",
    "to_xml",
]

__version__ = "0.1.0"

